{% set name = "epic-mace" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/18/c6/a0ce47960c0d2d2ff1310483cc89eb6e60978708b7e4b5226becff066a96/epic_mace-0.4.0.tar.gz
  sha256: 452c78e875dcdabb9d3c9a78e6356ad4ec6449065b0ead3039688c3f0f42fb1d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
    - rdkit >=2020.09
  run:
    - python >=3.7
    - rdkit >=2020.09

test:
  imports:
    - mace

about:
  home: "http://github.com/EPiCs-group/mace"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: 
  summary: "Python library and command-line tool for generation of 3D coordinates for complexes of d-/f-elements"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - 17598902
