{% set name = "epic-mace" %}
{% set version = "0.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/0c/78/539862f387c6a2e7d0e4f50f8b73a8b64af0146ad7867e8ca8e5a674eb91/epic_mace-0.3.4.tar.gz
  sha256: b6c7d1de5735108bf74394b7e4e66b74eb6f0c374c6869f63502147ce0f1bad4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - rdkit >=2020.09
  run:
    - python >=3.7
    - rdkit >=2020.09

test:
  imports:
    - mace

about:
  home: "http://github.com/EPiCs-group/mace"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: 
  summary: "Python library and command-line tool for generation of 3D coordinates for complexes of d-/f-elements"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - 17598902
