{% set name = "epic-mace" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/7d/ff/3c6019615318e20345af2a854aba2138fbb3f97055897656e20a24b9b182/epic_mace-0.5.0.tar.gz
  sha256: d59bf7986f5e5c00137ffb07b01f04f7ae022d7a73c995b0f6bb5efb720b9e21

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - epic-mace = mace.__main__:main
    - epic-mace-quickstart = mace._cli_quickstart:main

requirements:
  host:
    - pip
    - python >=3.7,<3.8.0a0
    - rdkit >=2020.09,<2021.03
    - numpy
    - pyyaml
  run:
    - python >=3.7,<3.8.0a0
    - rdkit >=2020.09,<2021.03
    - numpy
    - pyyaml

test:
  imports:
    - mace

about:
  home: "http://github.com/EPiCs-group/mace"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: 
  summary: "Toolkit for the automated screening and discovery of octahedral and square-planar mononuclear metal complexes"
  doc_url: "https://epic-mace.readthedocs.io/en/latest/"
  dev_url: "http://github.com/EPiCs-group/mace"
