channels:
  - rdkit
  - conda-forge
dependencies:
  - rdkit=2020.09
  - python=3.7
  - pip
  - pip:
    - myst-nb
    - myst-parser
    - nbclient
    - nbsphinx
    - sphinx
    - sphinx-gallery<0.11
    - sphinx-rtd-theme
